"""Turn a .tflite into a C array the firmware can embed.

    python tools/tflite_to_c.py model.tflite -o model_data.cpp

The firmware build runs this itself for the *_custom targets, on CUSTOM_MODEL
(firmware/CMakeLists.txt). Standard library only, so any python3 will do.

Emits the same symbols pico-tflmicro's own model file declares, so a firmware
target can link this instead of the baseline without touching any source:

    const unsigned char g_person_detect_model_data[]
    const int g_person_detect_model_data_len

16-byte aligned, which TFLite Micro requires of the flatbuffer.
"""
from __future__ import annotations

import argparse
import datetime
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("tflite", type=Path)
    ap.add_argument("-o", "--output", type=Path, required=True)
    args = ap.parse_args()

    blob = args.tflite.read_bytes()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by tools/tflite_to_c.py - do not edit.",
        f"// source: {args.tflite}",
        f"// bytes:  {len(blob):,}",
        f"// date:   {datetime.date.today().isoformat()}",
        "",
        "#include \"person_detect_model_data.h\"",
        "",
        "alignas(16) const unsigned char g_person_detect_model_data[] = {",
    ]
    for i in range(0, len(blob), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in blob[i:i + 12]))
    lines.append("};")
    lines.append(f"const int g_person_detect_model_data_len = {len(blob)};")
    lines.append("")
    args.output.write_text("\n".join(lines))
    print(f"{len(blob):,} bytes -> {args.output} ({args.output.stat().st_size / 1e6:.1f} MB of C)")


if __name__ == "__main__":
    main()
